const areaJson = {
  cityList: [
    {
      id: "320000",
      business_code: "",
      business_name: "江苏",
      business_level: "0",
      business_desc: "",
      parent_id: "",
      create_time: "1622189535",
      business_type: "region",
      business_type_name: "地域",
      display_index: "10",
    },
    {
      id: "320100",
      business_code: "",
      business_name: "南京市",
      business_level: "1",
      business_desc: "",
      parent_id: "320000",
      create_time: "1622189535",
      business_type: "region",
      business_type_name: "地域",
      display_index: "40",
    },
    {
      id: "320101",
      business_code: "",
      business_name: "南京市市辖区",
      business_level: "2",
      business_desc: "",
      parent_id: "320100",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320101",
    },
    {
      id: "320102",
      business_code: "",
      business_name: "南京市玄武区",
      business_level: "2",
      business_desc: "",
      parent_id: "320100",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320102",
    },
    {
      id: "320103",
      business_code: "",
      business_name: "南京市白下区",
      business_level: "2",
      business_desc: "",
      parent_id: "320100",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320103",
    },
    {
      id: "320104",
      business_code: "",
      business_name: "南京市秦淮区",
      business_level: "2",
      business_desc: "",
      parent_id: "320100",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320104",
    },
    {
      id: "320105",
      business_code: "",
      business_name: "南京市建邺区",
      business_level: "2",
      business_desc: "",
      parent_id: "320100",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320105",
    },
    {
      id: "320106",
      business_code: "",
      business_name: "南京市鼓楼区",
      business_level: "2",
      business_desc: "",
      parent_id: "320100",
      create_time: "1622189535",
      business_type: "region",
      business_type_name: "地域",
      display_index: "41",
    },
    {
      id: "320107",
      business_code: "",
      business_name: "南京市下关区",
      business_level: "2",
      business_desc: "",
      parent_id: "320100",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320107",
    },
    {
      id: "320111",
      business_code: "",
      business_name: "南京市浦口区",
      business_level: "2",
      business_desc: "",
      parent_id: "320100",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320111",
    },
    {
      id: "320113",
      business_code: "",
      business_name: "南京市栖霞区",
      business_level: "2",
      business_desc: "",
      parent_id: "320100",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320113",
    },
    {
      id: "320114",
      business_code: "",
      business_name: "南京市雨花台区",
      business_level: "2",
      business_desc: "",
      parent_id: "320100",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320114",
    },
    {
      id: "320115",
      business_code: "",
      business_name: "南京市江宁区",
      business_level: "2",
      business_desc: "",
      parent_id: "320100",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320115",
    },
    {
      id: "320116",
      business_code: "",
      business_name: "南京市六合区",
      business_level: "2",
      business_desc: "",
      parent_id: "320100",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320116",
    },
    {
      id: "320124",
      business_code: "",
      business_name: "南京市溧水县",
      business_level: "2",
      business_desc: "",
      parent_id: "320100",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320124",
    },
    {
      id: "320125",
      business_code: "",
      business_name: "南京市高淳县",
      business_level: "2",
      business_desc: "",
      parent_id: "320100",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320125",
    },
    {
      id: "320200",
      business_code: "",
      business_name: "无锡市",
      business_level: "1",
      business_desc: "",
      parent_id: "320000",
      create_time: "1622189535",
      business_type: "region",
      business_type_name: "地域",
      display_index: "50",
    },
    {
      id: "320201",
      business_code: "",
      business_name: "市辖区",
      business_level: "2",
      business_desc: "",
      parent_id: "320200",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320201",
    },
    {
      id: "320202",
      business_code: "",
      business_name: "崇安区",
      business_level: "2",
      business_desc: "",
      parent_id: "320200",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320202",
    },
    {
      id: "320203",
      business_code: "",
      business_name: "南长区",
      business_level: "2",
      business_desc: "",
      parent_id: "320200",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320203",
    },
    {
      id: "320204",
      business_code: "",
      business_name: "北塘区",
      business_level: "2",
      business_desc: "",
      parent_id: "320200",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320204",
    },
    {
      id: "320205",
      business_code: "",
      business_name: "锡山区",
      business_level: "2",
      business_desc: "",
      parent_id: "320200",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320205",
    },
    {
      id: "320206",
      business_code: "",
      business_name: "惠山区",
      business_level: "2",
      business_desc: "",
      parent_id: "320200",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320206",
    },
    {
      id: "320211",
      business_code: "",
      business_name: "滨湖区",
      business_level: "2",
      business_desc: "",
      parent_id: "320200",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320211",
    },
    {
      id: "320281",
      business_code: "",
      business_name: "江阴市",
      business_level: "2",
      business_desc: "",
      parent_id: "320200",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320281",
    },
    {
      id: "320282",
      business_code: "",
      business_name: "宜兴市",
      business_level: "2",
      business_desc: "",
      parent_id: "320200",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320282",
    },
    {
      id: "320300",
      business_code: "",
      business_name: "徐州市",
      business_level: "1",
      business_desc: "",
      parent_id: "320000",
      create_time: "1622189535",
      business_type: "region",
      business_type_name: "地域",
      display_index: "60",
    },
    {
      id: "320301",
      business_code: "",
      business_name: "市辖区",
      business_level: "2",
      business_desc: "",
      parent_id: "320300",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320301",
    },
    {
      id: "320302",
      business_code: "",
      business_name: "鼓楼区",
      business_level: "2",
      business_desc: "",
      parent_id: "320300",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320302",
    },
    {
      id: "320303",
      business_code: "",
      business_name: "云龙区",
      business_level: "2",
      business_desc: "",
      parent_id: "320300",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320303",
    },
    {
      id: "320305",
      business_code: "",
      business_name: "贾汪区",
      business_level: "2",
      business_desc: "",
      parent_id: "320300",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320305",
    },
    {
      id: "320311",
      business_code: "",
      business_name: "泉山区",
      business_level: "2",
      business_desc: "",
      parent_id: "320300",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320311",
    },
    {
      id: "320312",
      business_code: "",
      business_name: "铜山区",
      business_level: "2",
      business_desc: "",
      parent_id: "320300",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320312",
    },
    {
      id: "320321",
      business_code: "",
      business_name: "丰  县",
      business_level: "2",
      business_desc: "",
      parent_id: "320300",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320321",
    },
    {
      id: "320322",
      business_code: "",
      business_name: "沛  县",
      business_level: "2",
      business_desc: "",
      parent_id: "320300",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320322",
    },
    {
      id: "320324",
      business_code: "",
      business_name: "睢宁县",
      business_level: "2",
      business_desc: "",
      parent_id: "320300",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320324",
    },
    {
      id: "320381",
      business_code: "",
      business_name: "新沂市",
      business_level: "2",
      business_desc: "",
      parent_id: "320300",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320381",
    },
    {
      id: "320382",
      business_code: "",
      business_name: "邳州市",
      business_level: "2",
      business_desc: "",
      parent_id: "320300",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320382",
    },
    {
      id: "320400",
      business_code: "",
      business_name: "常州市",
      business_level: "1",
      business_desc: "",
      parent_id: "320000",
      create_time: "1622189535",
      business_type: "region",
      business_type_name: "地域",
      display_index: "70",
    },
    {
      id: "320401",
      business_code: "",
      business_name: "市辖区",
      business_level: "2",
      business_desc: "",
      parent_id: "320400",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320401",
    },
    {
      id: "320402",
      business_code: "",
      business_name: "天宁区",
      business_level: "2",
      business_desc: "",
      parent_id: "320400",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320402",
    },
    {
      id: "320404",
      business_code: "",
      business_name: "钟楼区",
      business_level: "2",
      business_desc: "",
      parent_id: "320400",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320404",
    },
    {
      id: "320405",
      business_code: "",
      business_name: "戚墅堰区",
      business_level: "2",
      business_desc: "",
      parent_id: "320400",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320405",
    },
    {
      id: "320411",
      business_code: "",
      business_name: "新北区",
      business_level: "2",
      business_desc: "",
      parent_id: "320400",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320411",
    },
    {
      id: "320412",
      business_code: "",
      business_name: "武进区",
      business_level: "2",
      business_desc: "",
      parent_id: "320400",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320412",
    },
    {
      id: "320481",
      business_code: "",
      business_name: "溧阳市",
      business_level: "2",
      business_desc: "",
      parent_id: "320400",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320481",
    },
    {
      id: "320482",
      business_code: "",
      business_name: "金坛市",
      business_level: "2",
      business_desc: "",
      parent_id: "320400",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320482",
    },
    {
      id: "320500",
      business_code: "",
      business_name: "苏州市",
      business_level: "1",
      business_desc: "",
      parent_id: "320000",
      create_time: "1622189535",
      business_type: "region",
      business_type_name: "地域",
      display_index: "30",
    },
    {
      id: "320501",
      business_code: "",
      business_name: "市辖区",
      business_level: "2",
      business_desc: "",
      parent_id: "320500",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320501",
    },
    {
      id: "320505",
      business_code: "",
      business_name: "虎丘区",
      business_level: "2",
      business_desc: "",
      parent_id: "320500",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320505",
    },
    {
      id: "320506",
      business_code: "",
      business_name: "吴中区",
      business_level: "2",
      business_desc: "",
      parent_id: "320500",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320506",
    },
    {
      id: "320507",
      business_code: "",
      business_name: "相城区",
      business_level: "2",
      business_desc: "",
      parent_id: "320500",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320507",
    },
    {
      id: "320508",
      business_code: "",
      business_name: "姑苏区",
      business_level: "2",
      business_desc: "",
      parent_id: "320500",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320508",
    },
    {
      id: "320509",
      business_code: "",
      business_name: "吴江区",
      business_level: "2",
      business_desc: "",
      parent_id: "320500",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320509",
    },
    {
      id: "320581",
      business_code: "",
      business_name: "常熟市",
      business_level: "2",
      business_desc: "",
      parent_id: "320500",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320581",
    },
    {
      id: "320582",
      business_code: "",
      business_name: "张家港市",
      business_level: "2",
      business_desc: "",
      parent_id: "320500",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320582",
    },
    {
      id: "320583",
      business_code: "",
      business_name: "昆山市",
      business_level: "2",
      business_desc: "",
      parent_id: "320500",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320583",
    },
    {
      id: "320585",
      business_code: "",
      business_name: "太仓市",
      business_level: "2",
      business_desc: "",
      parent_id: "320500",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320585",
    },
    {
      id: "320600",
      business_code: "",
      business_name: "南通市",
      business_level: "1",
      business_desc: "",
      parent_id: "320000",
      create_time: "1622189535",
      business_type: "region",
      business_type_name: "地域",
      display_index: "110",
    },
    {
      id: "320601",
      business_code: "",
      business_name: "市辖区",
      business_level: "2",
      business_desc: "",
      parent_id: "320600",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320601",
    },
    {
      id: "320602",
      business_code: "",
      business_name: "崇川区",
      business_level: "2",
      business_desc: "",
      parent_id: "320600",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320602",
    },
    {
      id: "320611",
      business_code: "",
      business_name: "港闸区",
      business_level: "2",
      business_desc: "",
      parent_id: "320600",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320611",
    },
    {
      id: "320612",
      business_code: "",
      business_name: "通州区",
      business_level: "2",
      business_desc: "",
      parent_id: "320600",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320612",
    },
    {
      id: "320621",
      business_code: "",
      business_name: "海安县",
      business_level: "2",
      business_desc: "",
      parent_id: "320600",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320621",
    },
    {
      id: "320623",
      business_code: "",
      business_name: "如东县",
      business_level: "2",
      business_desc: "",
      parent_id: "320600",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320623",
    },
    {
      id: "320681",
      business_code: "",
      business_name: "启动市",
      business_level: "2",
      business_desc: "",
      parent_id: "320600",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320681",
    },
    {
      id: "320682",
      business_code: "",
      business_name: "如皋市",
      business_level: "2",
      business_desc: "",
      parent_id: "320600",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320682",
    },
    {
      id: "320684",
      business_code: "",
      business_name: "海门市",
      business_level: "2",
      business_desc: "",
      parent_id: "320600",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320684",
    },
    {
      id: "320700",
      business_code: "",
      business_name: "连云港市",
      business_level: "1",
      business_desc: "",
      parent_id: "320000",
      create_time: "1622189535",
      business_type: "region",
      business_type_name: "地域",
      display_index: "20",
    },
    {
      id: "320701",
      business_code: "",
      business_name: "市辖区",
      business_level: "2",
      business_desc: "",
      parent_id: "320700",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320701",
    },
    {
      id: "320703",
      business_code: "",
      business_name: "连云区",
      business_level: "2",
      business_desc: "",
      parent_id: "320700",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320703",
    },
    {
      id: "320705",
      business_code: "",
      business_name: "新浦区",
      business_level: "2",
      business_desc: "",
      parent_id: "320700",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320705",
    },
    {
      id: "320706",
      business_code: "",
      business_name: "海州区",
      business_level: "2",
      business_desc: "",
      parent_id: "320700",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320706",
    },
    {
      id: "320721",
      business_code: "",
      business_name: "赣榆县",
      business_level: "2",
      business_desc: "",
      parent_id: "320700",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320721",
    },
    {
      id: "320722",
      business_code: "",
      business_name: "东海县",
      business_level: "2",
      business_desc: "",
      parent_id: "320700",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320722",
    },
    {
      id: "320723",
      business_code: "",
      business_name: "灌云县",
      business_level: "2",
      business_desc: "",
      parent_id: "320700",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320723",
    },
    {
      id: "320724",
      business_code: "",
      business_name: "灌南县",
      business_level: "2",
      business_desc: "",
      parent_id: "320700",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320724",
    },
    {
      id: "320800",
      business_code: "",
      business_name: "淮安市",
      business_level: "1",
      business_desc: "",
      parent_id: "320000",
      create_time: "1622189535",
      business_type: "region",
      business_type_name: "地域",
      display_index: "130",
    },
    {
      id: "320801",
      business_code: "",
      business_name: "市辖区",
      business_level: "2",
      business_desc: "",
      parent_id: "320800",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320801",
    },
    {
      id: "320802",
      business_code: "",
      business_name: "清河区",
      business_level: "2",
      business_desc: "",
      parent_id: "320800",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320802",
    },
    {
      id: "320803",
      business_code: "",
      business_name: "淮安区",
      business_level: "2",
      business_desc: "",
      parent_id: "320800",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320803",
    },
    {
      id: "320804",
      business_code: "",
      business_name: "淮阴区",
      business_level: "2",
      business_desc: "",
      parent_id: "320800",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320804",
    },
    {
      id: "320811",
      business_code: "",
      business_name: "青浦区",
      business_level: "2",
      business_desc: "",
      parent_id: "320800",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320811",
    },
    {
      id: "320826",
      business_code: "",
      business_name: "涟水县",
      business_level: "2",
      business_desc: "",
      parent_id: "320800",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320826",
    },
    {
      id: "320829",
      business_code: "",
      business_name: "洪泽县",
      business_level: "2",
      business_desc: "",
      parent_id: "320800",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320829",
    },
    {
      id: "320830",
      business_code: "",
      business_name: "盱眙县",
      business_level: "2",
      business_desc: "",
      parent_id: "320800",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320830",
    },
    {
      id: "320831",
      business_code: "",
      business_name: "金湖县",
      business_level: "2",
      business_desc: "",
      parent_id: "320800",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320831",
    },
    {
      id: "320900",
      business_code: "",
      business_name: "盐城市",
      business_level: "1",
      business_desc: "",
      parent_id: "320000",
      create_time: "1622189535",
      business_type: "region",
      business_type_name: "地域",
      display_index: "120",
    },
    {
      id: "320901",
      business_code: "",
      business_name: "市辖区",
      business_level: "2",
      business_desc: "",
      parent_id: "320900",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320901",
    },
    {
      id: "320902",
      business_code: "",
      business_name: "亭湖区",
      business_level: "2",
      business_desc: "",
      parent_id: "320900",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320902",
    },
    {
      id: "320903",
      business_code: "",
      business_name: "盐都区",
      business_level: "2",
      business_desc: "",
      parent_id: "320900",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320903",
    },
    {
      id: "320921",
      business_code: "",
      business_name: "响水县",
      business_level: "2",
      business_desc: "",
      parent_id: "320900",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320921",
    },
    {
      id: "320922",
      business_code: "",
      business_name: "滨海县",
      business_level: "2",
      business_desc: "",
      parent_id: "320900",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320922",
    },
    {
      id: "320923",
      business_code: "",
      business_name: "阜宁县",
      business_level: "2",
      business_desc: "",
      parent_id: "320900",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320923",
    },
    {
      id: "320924",
      business_code: "",
      business_name: "射阳县",
      business_level: "2",
      business_desc: "",
      parent_id: "320900",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320924",
    },
    {
      id: "320925",
      business_code: "",
      business_name: "建湖县",
      business_level: "2",
      business_desc: "",
      parent_id: "320900",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320925",
    },
    {
      id: "320981",
      business_code: "",
      business_name: "东台市",
      business_level: "2",
      business_desc: "",
      parent_id: "320900",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320981",
    },
    {
      id: "320982",
      business_code: "",
      business_name: "大丰市",
      business_level: "2",
      business_desc: "",
      parent_id: "320900",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "320982",
    },
    {
      id: "321000",
      business_code: "",
      business_name: "扬州市",
      business_level: "1",
      business_desc: "",
      parent_id: "320000",
      create_time: "1622189535",
      business_type: "region",
      business_type_name: "地域",
      display_index: "90",
    },
    {
      id: "321001",
      business_code: "",
      business_name: "市辖区",
      business_level: "2",
      business_desc: "",
      parent_id: "321000",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "321001",
    },
    {
      id: "321002",
      business_code: "",
      business_name: "广陵区",
      business_level: "2",
      business_desc: "",
      parent_id: "321000",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "321002",
    },
    {
      id: "321003",
      business_code: "",
      business_name: "邗江区",
      business_level: "2",
      business_desc: "",
      parent_id: "321000",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "321003",
    },
    {
      id: "321012",
      business_code: "",
      business_name: "江都区",
      business_level: "2",
      business_desc: "",
      parent_id: "321000",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "321012",
    },
    {
      id: "321023",
      business_code: "",
      business_name: "宝应县",
      business_level: "2",
      business_desc: "",
      parent_id: "321000",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "321023",
    },
    {
      id: "321081",
      business_code: "",
      business_name: "仪征市",
      business_level: "2",
      business_desc: "",
      parent_id: "321000",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "321081",
    },
    {
      id: "321084",
      business_code: "",
      business_name: "高邮市",
      business_level: "2",
      business_desc: "",
      parent_id: "321000",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "321084",
    },
    {
      id: "321100",
      business_code: "",
      business_name: "镇江市",
      business_level: "1",
      business_desc: "",
      parent_id: "320000",
      create_time: "1622189535",
      business_type: "region",
      business_type_name: "地域",
      display_index: "80",
    },
    {
      id: "321101",
      business_code: "",
      business_name: "市辖区",
      business_level: "2",
      business_desc: "",
      parent_id: "321100",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "321101",
    },
    {
      id: "321102",
      business_code: "",
      business_name: "京口区",
      business_level: "2",
      business_desc: "",
      parent_id: "321100",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "321102",
    },
    {
      id: "321111",
      business_code: "",
      business_name: "润州区",
      business_level: "2",
      business_desc: "",
      parent_id: "321100",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "321111",
    },
    {
      id: "321112",
      business_code: "",
      business_name: "丹徒区",
      business_level: "2",
      business_desc: "",
      parent_id: "321100",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "321112",
    },
    {
      id: "321181",
      business_code: "",
      business_name: "丹阳市",
      business_level: "2",
      business_desc: "",
      parent_id: "321100",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "321181",
    },
    {
      id: "321182",
      business_code: "",
      business_name: "扬中市",
      business_level: "2",
      business_desc: "",
      parent_id: "321100",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "321182",
    },
    {
      id: "321183",
      business_code: "",
      business_name: "句容市",
      business_level: "2",
      business_desc: "",
      parent_id: "321100",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "321183",
    },
    {
      id: "321200",
      business_code: "",
      business_name: "泰州市",
      business_level: "1",
      business_desc: "",
      parent_id: "320000",
      create_time: "1622189535",
      business_type: "region",
      business_type_name: "地域",
      display_index: "100",
    },
    {
      id: "321201",
      business_code: "",
      business_name: "市辖区",
      business_level: "2",
      business_desc: "",
      parent_id: "321200",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "321201",
    },
    {
      id: "321202",
      business_code: "",
      business_name: "海陵区",
      business_level: "2",
      business_desc: "",
      parent_id: "321200",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "321202",
    },
    {
      id: "321203",
      business_code: "",
      business_name: "高港区",
      business_level: "2",
      business_desc: "",
      parent_id: "321200",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "321203",
    },
    {
      id: "321281",
      business_code: "",
      business_name: "兴化市",
      business_level: "2",
      business_desc: "",
      parent_id: "321200",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "321281",
    },
    {
      id: "321282",
      business_code: "",
      business_name: "靖江市",
      business_level: "2",
      business_desc: "",
      parent_id: "321200",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "321282",
    },
    {
      id: "321283",
      business_code: "",
      business_name: "泰兴市",
      business_level: "2",
      business_desc: "",
      parent_id: "321200",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "321283",
    },
    {
      id: "321284",
      business_code: "",
      business_name: "姜堰市",
      business_level: "2",
      business_desc: "",
      parent_id: "321200",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "321284",
    },
    {
      id: "321300",
      business_code: "",
      business_name: "宿迁市",
      business_level: "1",
      business_desc: "",
      parent_id: "320000",
      create_time: "1622189535",
      business_type: "region",
      business_type_name: "地域",
      display_index: "140",
    },
    {
      id: "321301",
      business_code: "",
      business_name: "市辖区",
      business_level: "2",
      business_desc: "",
      parent_id: "321300",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "321301",
    },
    {
      id: "321302",
      business_code: "",
      business_name: "宿城区",
      business_level: "2",
      business_desc: "",
      parent_id: "321300",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "321302",
    },
    {
      id: "321311",
      business_code: "",
      business_name: "宿豫区",
      business_level: "2",
      business_desc: "",
      parent_id: "321300",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "321311",
    },
    {
      id: "321322",
      business_code: "",
      business_name: "沭阳县",
      business_level: "2",
      business_desc: "",
      parent_id: "321300",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "321322",
    },
    {
      id: "321323",
      business_code: "",
      business_name: "泗阳县",
      business_level: "2",
      business_desc: "",
      parent_id: "321300",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "321323",
    },
    {
      id: "321324",
      business_code: "",
      business_name: "泗洪县",
      business_level: "2",
      business_desc: "",
      parent_id: "321300",
      create_time: "1622189544",
      business_type: "region",
      business_type_name: "地域",
      display_index: "321324",
    },
    {
      id: "201912030100",
      business_code: "江苏省",
      business_name: "国网江苏省电力有限公司",
      business_level: "0",
      business_desc: "",
      parent_id: "",
      create_time: "1622189535",
      business_type: "corporation",
      business_type_name: "单位",
      display_index: "10",
    },
    {
      id: "201912030101",
      business_code: "南京",
      business_name: "南京供电公司",
      business_level: "1",
      business_desc: "",
      parent_id: "201912030100",
      create_time: "1622189535",
      business_type: "corporation",
      business_type_name: "单位",
      display_index: "20",
    },
    {
      id: "201912030102",
      business_code: "无锡",
      business_name: "无锡供电公司",
      business_level: "1",
      business_desc: "",
      parent_id: "201912030100",
      create_time: "1622189535",
      business_type: "corporation",
      business_type_name: "单位",
      display_index: "30",
    },
    {
      id: "201912030103",
      business_code: "南京本部",
      business_name: "南京供电公司本部",
      business_level: "2",
      business_desc: "",
      parent_id: "201912030101",
      create_time: "1622189535",
      business_type: "corporation",
      business_type_name: "单位",
      display_index: "40",
    },
    {
      id: "201912030104",
      business_code: "江北新区",
      business_name: "江北新区供电公司",
      business_level: "2",
      business_desc: "",
      parent_id: "201912030101",
      create_time: "1622189535",
      business_type: "corporation",
      business_type_name: "单位",
      display_index: "50",
    },
    {
      id: "201912030105",
      business_code: "溧水",
      business_name: "溧水区供电公司",
      business_level: "2",
      business_desc: "",
      parent_id: "201912030101",
      create_time: "1622189535",
      business_type: "corporation",
      business_type_name: "单位",
      display_index: "60",
    },
    {
      id: "201912030106",
      business_code: "高淳",
      business_name: "高淳区供电公司",
      business_level: "2",
      business_desc: "",
      parent_id: "201912030101",
      create_time: "1622189535",
      business_type: "corporation",
      business_type_name: "单位",
      display_index: "70",
    },
    {
      id: "201912030200",
      business_code: "",
      business_name: "台区",
      business_level: "0",
      business_desc: "",
      parent_id: "",
      create_time: "1622189535",
      business_type: "area",
      business_type_name: "站点",
      display_index: "0",
    },
    {
      id: "201912030201",
      business_code: "",
      business_name: "变电站",
      business_level: "0",
      business_desc: "",
      parent_id: "",
      create_time: "1622189535",
      business_type: "area",
      business_type_name: "站点",
      display_index: "0",
    },
    {
      id: "201912030202",
      business_code: "ganta",
      business_name: "杆塔",
      business_level: "0",
      business_desc: "",
      parent_id: "",
      create_time: "1622189535",
      business_type: "area",
      business_type_name: "站点",
      display_index: "10",
    },
    {
      id: "201912030203",
      business_code: "",
      business_name: "物联实验室模拟台区2",
      business_level: "1",
      business_desc: "",
      parent_id: "201912030200",
      create_time: "1622189535",
      business_type: "area",
      business_type_name: "站点",
      display_index: "0",
    },
    {
      id: "201912030204",
      business_code: "",
      business_name: "物联实验室模拟台区1",
      business_level: "1",
      business_desc: "",
      parent_id: "201912030200",
      create_time: "1622189535",
      business_type: "area",
      business_type_name: "站点",
      display_index: "0",
    },
    {
      id: "201912030205",
      business_code: "",
      business_name: "物联实验室模拟台区3",
      business_level: "1",
      business_desc: "",
      parent_id: "201912030200",
      create_time: "1622189535",
      business_type: "area",
      business_type_name: "站点",
      display_index: "0",
    },
    {
      id: "201912030206",
      business_code: "",
      business_name: "TEST-溧水-凤麟水源-2号配电房-5号台区",
      business_level: "1",
      business_desc: "",
      parent_id: "201912030200",
      create_time: "1622189535",
      business_type: "area",
      business_type_name: "站点",
      display_index: "0",
    },
    {
      id: "201912030207",
      business_code: "",
      business_name: "TEST-浦口-城南河变",
      business_level: "1",
      business_desc: "",
      parent_id: "201912030200",
      create_time: "1622189535",
      business_type: "area",
      business_type_name: "站点",
      display_index: "0",
    },
    {
      id: "201912030208",
      business_code: "",
      business_name: "TEST-溧水-凤麟水源-1号配电房-1号台区",
      business_level: "1",
      business_desc: "",
      parent_id: "201912030200",
      create_time: "1622189535",
      business_type: "area",
      business_type_name: "站点",
      display_index: "0",
    },
    {
      id: "201912030209",
      business_code: "",
      business_name: "TEST-溧水-凤麟水源-1号配电房-2号台区",
      business_level: "1",
      business_desc: "",
      parent_id: "201912030200",
      create_time: "1622189535",
      business_type: "area",
      business_type_name: "站点",
      display_index: "0",
    },
    {
      id: "201912030210",
      business_code: "",
      business_name: "TEST-溧水-凤麟水源-2号配电房-6号台区",
      business_level: "1",
      business_desc: "",
      parent_id: "201912030200",
      create_time: "1622189535",
      business_type: "area",
      business_type_name: "站点",
      display_index: "0",
    },
    {
      id: "201912030211",
      business_code: "",
      business_name: "TEST-溧水-凤麟水源-2号配电房-6号台区",
      business_level: "1",
      business_desc: "",
      parent_id: "201912030200",
      create_time: "0",
      business_type: "area",
      business_type_name: "站点",
      display_index: "0",
    },
  ],
};

function buildTree(data, parent_id = "") {
  let tree = [];
  for (const item of data) {
    if (item.business_type == "region" && item.parent_id === parent_id) {
      let children = buildTree(data, item.id);
      if (children.length > 0) {
        item.children = children;
      }
      tree.push(item);
    }
  }
  return tree;
}
export default buildTree(areaJson.cityList)
