export const authList={
    "code": "200",
    "message": "操作成功",
    "args": null,
    "ext": null,
    "data": {
        "records": [
            {
                "id": 1,
                "createBy": "admin",
                "createByView": null,
                "createTime": "2019-07-23 15:59:40",
                "updateBy": "admin",
                "updateByView": null,
                "updateTime": "2019-07-23 15:59:40",
                "version": 1,
                "parentTarget": null,
                "target": "access",
                "targetName": "用户权限",
                "action": "",
                "actionName": "",
                "deleteFlag": 0,
                "enableFlag": 1,
                "sort": 1,
                "accessKey": "89179297f058467d3ae656ba9234ae3d"
            },
            {
                "id": 2,
                "createBy": "admin",
                "createByView": null,
                "createTime": "2019-07-23 15:59:40",
                "updateBy": "admin",
                "updateByView": null,
                "updateTime": "2019-07-23 15:59:40",
                "version": 1,
                "parentTarget": null,
                "target": "report",
                "targetName": "报表设计",
                "action": "",
                "actionName": "",
                "deleteFlag": 0,
                "enableFlag": 1,
                "sort": 2,
                "accessKey": "1aec8e5d33aee82c021ba8df4c6b09e9"
            },
            {
                "id": 3,
                "createBy": "admin",
                "createByView": null,
                "createTime": "2019-07-23 15:59:40",
                "updateBy": "admin",
                "updateByView": null,
                "updateTime": "2019-07-23 15:59:40",
                "version": 1,
                "parentTarget": null,
                "target": "system",
                "targetName": "系统设置",
                "action": "",
                "actionName": "",
                "deleteFlag": 0,
                "enableFlag": 1,
                "sort": 3,
                "accessKey": "65bf7e6bd0981838bf89cbdb88c4ce91"
            },
            {
                "id": 101,
                "createBy": "admin",
                "createByView": null,
                "createTime": "2019-07-23 15:59:40",
                "updateBy": "admin",
                "updateByView": null,
                "updateTime": "2019-07-23 15:59:40",
                "version": 1,
                "parentTarget": "access",
                "target": "authorityManage",
                "targetName": "权限管理",
                "action": "insert",
                "actionName": "新增权限",
                "deleteFlag": 0,
                "enableFlag": 1,
                "sort": 101,
                "accessKey": "a340b172ebc3e2ab36096ea581f3df60"
            },
            {
                "id": 102,
                "createBy": "admin",
                "createByView": null,
                "createTime": "2019-07-23 15:59:40",
                "updateBy": "admin",
                "updateByView": null,
                "updateTime": "2019-07-23 15:59:40",
                "version": 1,
                "parentTarget": "access",
                "target": "authorityManage",
                "targetName": "权限管理",
                "action": "update",
                "actionName": "修改权限",
                "deleteFlag": 0,
                "enableFlag": 1,
                "sort": 102,
                "accessKey": "b488327c2a17f01a31238ffa26c280a4"
            },
            {
                "id": 103,
                "createBy": "admin",
                "createByView": null,
                "createTime": "2019-07-23 15:59:40",
                "updateBy": "admin",
                "updateByView": null,
                "updateTime": "2019-07-23 15:59:40",
                "version": 1,
                "parentTarget": "access",
                "target": "authorityManage",
                "targetName": "权限管理",
                "action": "delete",
                "actionName": "删除权限",
                "deleteFlag": 0,
                "enableFlag": 1,
                "sort": 103,
                "accessKey": "5908954270c5c8d2d94ae4e87c7d82ca"
            },
            {
                "id": 104,
                "createBy": "admin",
                "createByView": null,
                "createTime": "2019-07-23 15:59:40",
                "updateBy": "admin",
                "updateByView": null,
                "updateTime": "2019-07-23 15:59:40",
                "version": 1,
                "parentTarget": "access",
                "target": "authorityManage",
                "targetName": "权限管理",
                "action": "query",
                "actionName": "查询权限",
                "deleteFlag": 0,
                "enableFlag": 1,
                "sort": 104,
                "accessKey": "f161aeaa87b0e1b64944ec9503dfa860"
            },
            {
                "id": 105,
                "createBy": "admin",
                "createByView": null,
                "createTime": "2019-07-23 15:59:40",
                "updateBy": "admin",
                "updateByView": null,
                "updateTime": "2021-07-17 20:41:46",
                "version": 2,
                "parentTarget": "access",
                "target": "roleManage",
                "targetName": "角色管理",
                "action": "insert",
                "actionName": "新建角色",
                "deleteFlag": 0,
                "enableFlag": 1,
                "sort": 105,
                "accessKey": "2e4fe1238b6661f0d1ea1ba8f236831a"
            },
            {
                "id": 106,
                "createBy": "admin",
                "createByView": null,
                "createTime": "2019-07-23 15:59:40",
                "updateBy": "admin",
                "updateByView": null,
                "updateTime": "2019-07-23 15:59:40",
                "version": 1,
                "parentTarget": "access",
                "target": "roleManage",
                "targetName": "角色管理",
                "action": "update",
                "actionName": "修改角色",
                "deleteFlag": 0,
                "enableFlag": 1,
                "sort": 106,
                "accessKey": "0f0714383ffee0665cc453c959c0e362"
            },
            {
                "id": 107,
                "createBy": "admin",
                "createByView": null,
                "createTime": "2019-07-23 15:59:40",
                "updateBy": "admin",
                "updateByView": null,
                "updateTime": "2019-07-23 15:59:40",
                "version": 1,
                "parentTarget": "access",
                "target": "roleManage",
                "targetName": "角色管理",
                "action": "delete",
                "actionName": "删除角色",
                "deleteFlag": 0,
                "enableFlag": 1,
                "sort": 107,
                "accessKey": "3113bb04e4bcf596bd86807da4156c19"
            }
        ],
        "total": 70,
        "size": 10,
        "current": 1,
        "orders": [],
        "optimizeCountSql": true,
        "hitCount": false,
        "searchCount": true,
        "pages": 7
    }
}

export const authTree={
    "code": "200",
    "message": "操作成功",
    "args": null,
    "ext": null,
    "data": [
        {
            "id": "access",
            "label": "用户权限",
            "type": null,
            "icon": null,
            "parent": null,
            "resUrl": null,
            "children": [
                {
                    "id": "authorityManage",
                    "label": "权限管理",
                    "type": null,
                    "icon": null,
                    "parent": null,
                    "resUrl": null,
                    "children": []
                },
                {
                    "id": "roleManage",
                    "label": "角色管理",
                    "type": null,
                    "icon": null,
                    "parent": null,
                    "resUrl": null,
                    "children": []
                },
                {
                    "id": "userManage",
                    "label": "用户管理",
                    "type": null,
                    "icon": null,
                    "parent": null,
                    "resUrl": null,
                    "children": []
                }
            ]
        },
        {
            "id": "report",
            "label": "报表设计",
            "type": null,
            "icon": null,
            "parent": null,
            "resUrl": null,
            "children": [
                {
                    "id": "datasourceManage",
                    "label": "数据源管理",
                    "type": null,
                    "icon": null,
                    "parent": null,
                    "resUrl": null,
                    "children": []
                },
                {
                    "id": "resultsetManage",
                    "label": "数据集管理",
                    "type": null,
                    "icon": null,
                    "parent": null,
                    "resUrl": null,
                    "children": []
                },
                {
                    "id": "reportManage",
                    "label": "报表管理",
                    "type": null,
                    "icon": null,
                    "parent": null,
                    "resUrl": null,
                    "children": []
                },
                {
                    "id": "bigScreenManage",
                    "label": "大屏报表",
                    "type": null,
                    "icon": null,
                    "parent": null,
                    "resUrl": null,
                    "children": []
                },
                {
                    "id": "reportShareManage",
                    "label": "报表分享",
                    "type": null,
                    "icon": null,
                    "parent": null,
                    "resUrl": null,
                    "children": []
                },
                {
                    "id": "excelManage",
                    "label": "表格报表",
                    "type": null,
                    "icon": null,
                    "parent": null,
                    "resUrl": null,
                    "children": []
                }
            ]
        },
        {
            "id": "system",
            "label": "系统设置",
            "type": null,
            "icon": null,
            "parent": null,
            "resUrl": null,
            "children": [
                {
                    "id": "fileManage",
                    "label": "文件管理",
                    "type": null,
                    "icon": null,
                    "parent": null,
                    "resUrl": null,
                    "children": []
                },
                {
                    "id": "dictManage",
                    "label": "数据字典",
                    "type": null,
                    "icon": null,
                    "parent": null,
                    "resUrl": null,
                    "children": []
                },
                {
                    "id": "dictItemManage",
                    "label": "数据字典项",
                    "type": null,
                    "icon": null,
                    "parent": null,
                    "resUrl": null,
                    "children": []
                }
            ]
        }
    ]
}