/*
 * @Description: 
 * @Author: Wang Su
 * @Date: 2024-01-02 15:40:17
 * @LastEditors: Wang Su
 * @LastEditTime: 2024-01-02 15:40:17
 */
//大屏列表
export const bigScreenList={
    "code": "200",
    "message": "操作成功",
    "args": null,
    "ext": null,
    "data": {
        "records": [
            {
                "id": 204,
                "createBy": "admin",
                "createByView": null,
                "createTime": "2023-12-23 13:28:41",
                "updateBy": "admin",
                "updateByView": null,
                "updateTime": "2023-12-23 13:28:41",
                "version": 1,
                "reportName": "测试1",
                "reportCode": "bm1_1703309315052",
                "setCodes": null,
                "reportGroup": "default",
                "reportDesc": null,
                "setParam": null,
                "jsonStr": null,
                "reportType": "report_screen",
                "total": 0,
                "reportImage": null,
                "enableFlag": 1,
                "deleteFlag": 0,
                "reportAuthor": "zjl",
                "downloadCount": null,
                "accessKey": "9b4f881638dffd35289e0795cf3e2e02"
            },
            {
                "id": 202,
                "createBy": "admin",
                "createByView": null,
                "createTime": "2023-12-12 16:27:00",
                "updateBy": "admin",
                "updateByView": null,
                "updateTime": "2023-12-12 16:35:50",
                "version": 2,
                "reportName": "测试1",
                "reportCode": "bm1",
                "setCodes": null,
                "reportGroup": "default",
                "reportDesc": null,
                "setParam": null,
                "jsonStr": null,
                "reportType": "report_screen",
                "total": 0,
                "reportImage": null,
                "enableFlag": 1,
                "deleteFlag": 0,
                "reportAuthor": "zjl",
                "downloadCount": null,
                "accessKey": "ad40532a7ac88757f482bf925cd45d4b"
            },
            {
                "id": 201,
                "createBy": "admin",
                "createByView": null,
                "createTime": "2023-12-12 10:37:47",
                "updateBy": "admin",
                "updateByView": null,
                "updateTime": "2023-12-12 15:57:51",
                "version": 2,
                "reportName": "testtest",
                "reportCode": "test",
                "setCodes": null,
                "reportGroup": "default",
                "reportDesc": null,
                "setParam": null,
                "jsonStr": null,
                "reportType": "report_screen",
                "total": 0,
                "reportImage": null,
                "enableFlag": 1,
                "deleteFlag": 0,
                "reportAuthor": "yq",
                "downloadCount": 0,
                "accessKey": "a50b2b289fcf7df91c5e1880fbac3d98"
            },
            {
                "id": 200,
                "createBy": "admin",
                "createByView": null,
                "createTime": "2023-12-11 09:32:51",
                "updateBy": "admin",
                "updateByView": null,
                "updateTime": "2023-12-11 09:32:51",
                "version": 1,
                "reportName": "test1",
                "reportCode": "ws",
                "setCodes": null,
                "reportGroup": "default",
                "reportDesc": "ws",
                "setParam": null,
                "jsonStr": null,
                "reportType": "report_screen",
                "total": 0,
                "reportImage": null,
                "enableFlag": 1,
                "deleteFlag": 0,
                "reportAuthor": "ws",
                "downloadCount": null,
                "accessKey": "68ba48ccad77cde930e24a74579cdbf8"
            },
            {
                "id": 199,
                "createBy": "admin",
                "createByView": null,
                "createTime": "2023-05-09 10:38:59",
                "updateBy": "admin",
                "updateByView": null,
                "updateTime": "2023-05-09 10:38:59",
                "version": 1,
                "reportName": "表单测试",
                "reportCode": "testForm",
                "setCodes": null,
                "reportGroup": "default",
                "reportDesc": null,
                "setParam": null,
                "jsonStr": null,
                "reportType": "report_screen",
                "total": 0,
                "reportImage": null,
                "enableFlag": 1,
                "deleteFlag": 0,
                "reportAuthor": null,
                "downloadCount": null,
                "accessKey": "dd92620c9e9870d9b37d2166d2ea333a"
            },
            {
                "id": 197,
                "createBy": "admin",
                "createByView": null,
                "createTime": "2021-06-30 16:34:40",
                "updateBy": "admin",
                "updateByView": null,
                "updateTime": "2021-07-01 15:19:56",
                "version": 3,
                "reportName": "空白大屏",
                "reportCode": "blank",
                "setCodes": null,
                "reportGroup": null,
                "reportDesc": "",
                "setParam": null,
                "jsonStr": null,
                "reportType": "report_screen",
                "total": 0,
                "reportImage": "",
                "enableFlag": 1,
                "deleteFlag": 0,
                "reportAuthor": null,
                "downloadCount": null,
                "accessKey": "85ee20a7bd91dd733c7ad518f66e4dc6"
            },
            {
                "id": 196,
                "createBy": "admin",
                "createByView": null,
                "createTime": "2021-06-30 15:19:59",
                "updateBy": "admin",
                "updateByView": null,
                "updateTime": "2021-06-30 15:19:59",
                "version": 1,
                "reportName": "访问大屏",
                "reportCode": "acc_ajreport",
                "setCodes": null,
                "reportGroup": null,
                "reportDesc": "",
                "setParam": null,
                "jsonStr": null,
                "reportType": "report_screen",
                "total": 0,
                "reportImage": null,
                "enableFlag": 1,
                "deleteFlag": 0,
                "reportAuthor": null,
                "downloadCount": null,
                "accessKey": "6d361e62b85fa0b3545915e81dfeaf73"
            },
            {
                "id": 194,
                "createBy": "admin",
                "createByView": null,
                "createTime": "2021-06-30 10:06:31",
                "updateBy": "admin",
                "updateByView": null,
                "updateTime": "2021-06-30 10:06:31",
                "version": 1,
                "reportName": "日志大屏",
                "reportCode": "log_ajreport",
                "setCodes": null,
                "reportGroup": null,
                "reportDesc": "",
                "setParam": null,
                "jsonStr": null,
                "reportType": "report_screen",
                "total": 0,
                "reportImage": null,
                "enableFlag": 1,
                "deleteFlag": 0,
                "reportAuthor": null,
                "downloadCount": null,
                "accessKey": "00390b51db0c7a966425e5142c8e6377"
            }
        ],
        "total": 8,
        "size": 8,
        "current": 1,
        "orders": [],
        "optimizeCountSql": true,
        "hitCount": false,
        "searchCount": true,
        "pages": 1
    }
}